{{- if .Values.vault.enabled -}}
{{- range .Values.vault.secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
spec:
  refreshInterval: {{ $.Values.vault.refreshInterval }}
  secretStoreRef:
    name: {{ $.Values.vault.storeRef.name }}
    kind: {{ $.Values.vault.storeRef.kind }}
  target:
    name: {{ $.Release.Name }}-{{ .name }}
    creationPolicy: Owner
  data:
    {{- range .keys }}
    {{- range $envVar, $spec := . }}
    - secretKey: {{ $envVar }}
      remoteRef:
        key: {{ $spec.remoteKey }}
        property: {{ $spec.property }}
    {{- end }}
    {{- end }}
{{- end }}
{{- end }}
