# k3s HA cluster on Hetzner Cloud.
#
# Topology:
#   - 1 private network (cluster-internal traffic) per cluster.
#   - N control-plane servers (default 3): k3s server with embedded etcd.
#   - M worker servers (default 3): k3s agent.
#   - 1 hcloud Load Balancer in front of the control-plane API (port 6443).
#   - 1 hcloud Load Balancer in front of node ports 80/443 for ingress.
#   - Both LBs are TCP pass-through; TLS terminates inside the cluster
#     at Traefik (which gets certs from cert-manager via Cloudflare DNS-01).
#
# Public ingress is via Cloudflare Tunnel (`cloudflared`) — see
# infra/helm/cloudflared/. The ingress LB exists for the bootstrap window
# and for break-glass; in steady state nothing public should hit it.
#
# Bootstrap of k3s itself uses cloud-init:
#   - First control-plane node: `k3s server --cluster-init` (no token).
#   - Subsequent control-planes:`k3s server --server https://<lb>:6443 --token <shared>`.
#   - Workers: `k3s agent --server https://<lb>:6443 --token <shared>`.
# A random token is generated by the `random_password` resource; consumers
# read it from Vault after bootstrap.

terraform {
  required_providers {
    hcloud = { source = "hetznercloud/hcloud" }
    random = { source = "hashicorp/random" }
    tls    = { source = "hashicorp/tls" }
  }
}

resource "random_password" "k3s_token" {
  length  = 48
  special = false
}

resource "hcloud_ssh_key" "break_glass" {
  count      = length(var.ssh_public_keys)
  name       = "${var.cluster_name}-break-glass-${count.index}"
  public_key = var.ssh_public_keys[count.index]
  labels     = var.labels
}

resource "hcloud_network" "cluster" {
  name     = "${var.cluster_name}-net"
  ip_range = var.private_network_cidr
  labels   = var.labels
}

resource "hcloud_network_subnet" "nodes" {
  network_id   = hcloud_network.cluster.id
  type         = "cloud"
  network_zone = var.network_zone
  ip_range     = cidrsubnet(var.private_network_cidr, 8, 1)
}

resource "hcloud_placement_group" "control_plane" {
  name   = "${var.cluster_name}-control-plane"
  type   = "spread"
  labels = var.labels
}

resource "hcloud_placement_group" "workers" {
  name   = "${var.cluster_name}-workers"
  type   = "spread"
  labels = var.labels
}

# ----- Control plane ---------------------------------------------------------

resource "hcloud_server" "control_plane" {
  count              = var.control_plane_count
  name               = "${var.cluster_name}-cp-${count.index + 1}"
  server_type        = var.control_plane_server_type
  image              = var.image
  location           = var.location
  ssh_keys           = hcloud_ssh_key.break_glass[*].id
  placement_group_id = hcloud_placement_group.control_plane.id

  # Bootstrap script — first node initialises etcd, others join.
  user_data = templatefile("${path.module}/cloud-init/control-plane.yaml", {
    is_first   = count.index == 0
    join_url   = count.index == 0 ? "" : "https://${hcloud_load_balancer.control_plane.ipv4}:6443"
    k3s_token  = random_password.k3s_token.result
    node_index = count.index + 1
    cluster    = var.cluster_name
  })

  network {
    network_id = hcloud_network.cluster.id
  }

  labels = merge(var.labels, {
    role = "control-plane"
  })

  depends_on = [hcloud_network_subnet.nodes]
}

# ----- Workers ---------------------------------------------------------------

resource "hcloud_server" "worker" {
  count              = var.worker_count
  name               = "${var.cluster_name}-w-${count.index + 1}"
  server_type        = var.worker_server_type
  image              = var.image
  location           = var.location
  ssh_keys           = hcloud_ssh_key.break_glass[*].id
  placement_group_id = hcloud_placement_group.workers.id

  user_data = templatefile("${path.module}/cloud-init/worker.yaml", {
    join_url   = "https://${hcloud_load_balancer.control_plane.ipv4}:6443"
    k3s_token  = random_password.k3s_token.result
    node_index = count.index + 1
    cluster    = var.cluster_name
  })

  network {
    network_id = hcloud_network.cluster.id
  }

  labels = merge(var.labels, {
    role = "worker"
  })

  depends_on = [hcloud_server.control_plane]
}

# ----- Load balancers --------------------------------------------------------

resource "hcloud_load_balancer" "control_plane" {
  name               = "${var.cluster_name}-cp-lb"
  load_balancer_type = "lb11"
  location           = var.location
  labels             = var.labels
}

resource "hcloud_load_balancer_network" "control_plane" {
  load_balancer_id = hcloud_load_balancer.control_plane.id
  network_id       = hcloud_network.cluster.id
}

resource "hcloud_load_balancer_service" "k8s_api" {
  load_balancer_id = hcloud_load_balancer.control_plane.id
  protocol         = "tcp"
  listen_port      = 6443
  destination_port = 6443

  health_check {
    protocol = "tcp"
    port     = 6443
    interval = 10
    timeout  = 5
    retries  = 3
  }
}

resource "hcloud_load_balancer_target" "control_plane" {
  count            = var.control_plane_count
  type             = "server"
  load_balancer_id = hcloud_load_balancer.control_plane.id
  server_id        = hcloud_server.control_plane[count.index].id
  use_private_ip   = true
  depends_on       = [hcloud_load_balancer_network.control_plane]
}

resource "hcloud_load_balancer" "ingress" {
  name               = "${var.cluster_name}-ingress-lb"
  load_balancer_type = "lb11"
  location           = var.location
  labels             = var.labels
}

resource "hcloud_load_balancer_network" "ingress" {
  load_balancer_id = hcloud_load_balancer.ingress.id
  network_id       = hcloud_network.cluster.id
}

resource "hcloud_load_balancer_service" "http" {
  load_balancer_id = hcloud_load_balancer.ingress.id
  protocol         = "tcp"
  listen_port      = 80
  destination_port = 80
}

resource "hcloud_load_balancer_service" "https" {
  load_balancer_id = hcloud_load_balancer.ingress.id
  protocol         = "tcp"
  listen_port      = 443
  destination_port = 443
}

resource "hcloud_load_balancer_target" "ingress_workers" {
  count            = var.worker_count
  type             = "server"
  load_balancer_id = hcloud_load_balancer.ingress.id
  server_id        = hcloud_server.worker[count.index].id
  use_private_ip   = true
  depends_on       = [hcloud_load_balancer_network.ingress]
}

# ----- Kubeconfig fetch ------------------------------------------------------
# Cloud-init writes /etc/rancher/k3s/k3s.yaml on the first control-plane node.
# Operators retrieve it via the break-glass SSH key:
#
#   scp root@<cp-1>:/etc/rancher/k3s/k3s.yaml ./kubeconfig
#   sed -i "s/127.0.0.1/${LB_IP}/" ./kubeconfig
#
# We deliberately don't fetch it inside Terraform — that would require
# remote-exec which couples plan/apply to network reachability. The
# bootstrap runbook does it once.

resource "local_file" "kubeconfig_fetch_hint" {
  filename        = "${path.root}/.terraform/${var.cluster_name}-kubeconfig.hint"
  content         = "scp root@${hcloud_server.control_plane[0].ipv4_address}:/etc/rancher/k3s/k3s.yaml ./kubeconfig\nsed -i 's/127.0.0.1/${hcloud_load_balancer.control_plane.ipv4}/' ./kubeconfig\n"
  file_permission = "0600"
}
