import { Router, type IRouter } from "express";
import healthRouter from "./health";
import meRouter from "./me";
import countriesRouter from "./countries";
import productsRouter from "./products";
import streamsRouter from "./streams";
import replaysRouter from "./replays";
import fulfillmentLocationsRouter from "./fulfillmentLocations";
import promoCodesRouter from "./promoCodes";
import cartRouter from "./cart";
import checkoutDraftRouter from "./checkoutDraft";
import ordersRouter from "./orders";
import returnsRouter from "./returns";
import walletRouter from "./wallet";
import safetyRouter from "./safety";
import onboardingRouter from "./onboarding";
import notificationPrefsRouter from "./notificationPrefs";
import referralsRouter from "./referrals";
import followsRouter from "./follows";
import wishlistRouter from "./wishlist";
import reviewsRouter from "./reviews";
import discoveryRouter from "./discovery";
import sellerRouter from "./seller";
import paymentsRouter from "./payments";
import adminRouter from "./admin";
import authRouter from "./auth";
import pushTokensRouter from "./pushTokens";
import promosRouter from "./promos";
import fulfillmentRouter from "./fulfillment";
import boxRouter from "./box";
import pudoRouter from "./pudo";

const router: IRouter = Router();

router.use(healthRouter);
router.use(countriesRouter);
router.use(productsRouter);
router.use(streamsRouter);
router.use(replaysRouter);
router.use(fulfillmentLocationsRouter);
router.use(promoCodesRouter);
router.use(meRouter);
router.use(cartRouter);
router.use(checkoutDraftRouter);
router.use(ordersRouter);
router.use(returnsRouter);
router.use(walletRouter);
router.use(safetyRouter);
router.use(onboardingRouter);
router.use(notificationPrefsRouter);
router.use(referralsRouter);
router.use(followsRouter);
router.use(wishlistRouter);
router.use(reviewsRouter);
router.use(discoveryRouter);
router.use(sellerRouter);
router.use(paymentsRouter);
router.use(adminRouter);
router.use(authRouter);
router.use(pushTokensRouter);
router.use(promosRouter);
router.use(fulfillmentRouter);
router.use(boxRouter);
router.use(pudoRouter);

export default router;
