apiVersion: v2
name: external-secrets-platform
description: Wrapper around external-secrets/external-secrets operator.
type: application
version: 0.1.0
appVersion: "0.10"
dependencies:
  - name: external-secrets
    version: 0.10.7
    repository: https://charts.external-secrets.io
