apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-monolith.fullname" . }}
  labels: {{- include "api-monolith.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector: {{- include "api-monolith.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "api-monolith.fullname" . }}
  labels: {{- include "api-monolith.labels" . | nindent 4 }}
